vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set cursorline")
vim.g.mapleader = " "

vim.keymap.set('n', '<leader>s', "<cmd>w<cr>", { desc = "Save" })
vim.keymap.set('n', '<leader>q', "<cmd>confirm q<cr>", { desc = "Quit" })
vim.keymap.set('n', '<leader>Q', "<cmd>confirm qall<cr>", { desc = "Quit All" })
vim.keymap.set('n', '<leader>wh', "<C-w>h", { desc = "Move to left split" })
vim.keymap.set('n', '<leader>wj', "<C-w>j", { desc = "Move to below split" })
vim.keymap.set('n', '<leader>wk', "<C-w>k", { desc = "Move to above split" })
vim.keymap.set('n', '<leader>wl', "<C-w>l", { desc = "Move to right split" })
vim.keymap.set('n', '<C-Up>', "<cmd>resize -1<CR>", { desc = "Resize split up" })
vim.keymap.set('n', '<C-Down>', "<cmd>resize +1<CR>", { desc = "Resize split down" })
vim.keymap.set('n', '<C-Left>', "<cmd>vertical resize -1<CR>", { desc = "Resize split left" })
vim.keymap.set('n', '<C-Right>', "<cmd>vertical resize +1<CR>", { desc = "Resize split right" })
vim.keymap.set('n', '<leader>wv', "<cmd>vsplit<cr>", { desc = "Vertical Split" })
vim.keymap.set('n', '<leader>ws', "<cmd>split<cr>", { desc = "Horizontal Split" })
vim.keymap.set('n', '<leader>tl', function() vim.cmd.tabnext() end, { desc = "Next tab" })
vim.keymap.set('n', '<leader>th', function() vim.cmd.tabprevious() end, { desc = "Previous tab" })
vim.keymap.set('n', '<leader>tn', function() vim.cmd.tabnew() end, { desc = "New tab" })
vim.keymap.set('n', '<leader>tc', function() vim.cmd.tabclose() end, { desc = "Close tab" })
